// Run through the installed Tabbit browser runtime (top-level return is intentional).
globalThis.atlasErrors = [];
await page.reload({ waitUntil: 'networkidle' });
if (globalThis.originalAtlas) {
  await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(globalThis.originalAtlas)});
  await page.getByRole('button',{name:'确认导入',exact:true}).click();
}
await page.getByRole('button', { name: '保存', exact: true }).click();
globalThis.originalAtlas = await page.evaluate(() => localStorage.getItem('novel-atlas-v1'));
const results = [];
await page.getByRole('button', { name: '新增角色', exact: true }).click();
await page.getByRole('textbox', { name: '角色名称' }).fill('测试旅人');
await page.getByRole('combobox', { name: '所属阵营' }).fill('测试阵营');
await page.getByRole('textbox', { name: '人物小传' }).fill('用于验证新增、编辑和持久化。');
await page.getByRole('dialog').getByRole('button', { name: '添加角色', exact: true }).click();
await expect(page.locator('.status-bar')).toContainText('13 位角色');
await expect(page.locator('.profile h2')).toHaveText('测试旅人');
results.push('新增角色及详情显示');
await page.getByRole('button', { name: '编辑档案', exact: true }).click();
await page.getByRole('textbox', { name: '角色名称' }).fill('旅人改名');
await page.getByRole('dialog').getByRole('button', { name: '保存修改' }).click();
await expect(page.locator('.profile h2')).toHaveText('旅人改名');
await page.getByRole('button', { name: '添加关系', exact: true }).click();
await page.getByRole('combobox', { name: '终点角色' }).selectOption({label:'花盈'});
await page.getByRole('textbox', { name: '关系名称' }).fill('同行');
await page.getByRole('button', {name: '双向关系 起点 ↔ 终点'}).click();
await page.getByRole('textbox', {name: '关系描述'}).fill('同路而行');
await page.getByRole('button', {name: '保存关系', exact: true}).click();
await expect(page.locator('.relation-profile h2')).toHaveText('同行');
await expect(page.locator('.status-bar')).toContainText('19 条关系');
results.push('改名与双向关系创建');
await page.getByRole('button', {name: '编辑关系', exact: true}).click();
await page.getByRole('textbox', {name: '关系名称'}).fill('挚友');
await page.getByRole('button', {name: '保存关系', exact: true}).click();
await page.reload({waitUntil:'networkidle'});
await expect(page.locator('.status-bar')).toContainText('13 位角色');
await expect(page.locator('.status-bar')).toContainText('19 条关系');
const stored = JSON.parse(await page.evaluate(() => localStorage.getItem('novel-atlas-v1')));
expect(stored.characters.find(c => c.name === '旅人改名')).toBeTruthy();
expect(stored.relations.at(-1).label).toBe('挚友');
expect(stored.relations.at(-1).direction).toBe('two-way');
results.push('关系修改与刷新恢复');
await page.getByRole('textbox', {name:'搜索角色',exact:true}).fill('旅人改名');
await expect(page.locator('.character-item')).toHaveCount(1);
await page.locator('.character-item').click();
await page.getByRole('button',{name:'删除当前角色',exact:true}).click();
await page.getByRole('button',{name:'确认删除',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('12 位角色');
await expect(page.locator('.status-bar')).toContainText('18 条关系');
await page.getByRole('button',{name:'撤销',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('13 位角色');
await expect(page.locator('.status-bar')).toContainText('19 条关系');
await page.getByRole('button',{name:'重做',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('12 位角色');
results.push('搜索、删除级联、撤销与重做');
await page.getByRole('button',{name:'清除搜索',exact:true}).click();
const invalid = {characters:[{id:'duplicate',name:'甲'},{id:'duplicate',name:'乙'}],relations:[]};
await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'duplicate.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});
await expect(page.getByRole('status')).toContainText('重复');
await expect(page.locator('.status-bar')).toContainText('12 位角色');
results.push('错误导入不会覆盖当前图谱');
const parallel = {version:1,title:'平行关系测试',characters:[{id:'a',name:'甲'},{id:'b',name:'乙'}],relations:[{from:'a',to:'b',label:'朋友',direction:'two-way'},{from:'a',to:'b',label:'敌人',direction:'one-way'}]};
await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'parallel.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(parallel))});
await expect(page.getByRole('dialog')).toContainText('2 位角色 · 2 条关系');
await page.getByRole('button',{name:'确认导入',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('2 位角色');
await expect(page.locator('.status-bar')).toContainText('2 条关系');
await page.getByRole('button',{name:'添加关系',exact:true}).click();
await page.getByRole('textbox',{name:'关系名称'}).fill('师徒');
await page.getByRole('button',{name:'保存关系',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('3 条关系');
results.push('JSON 导入预览与同对角色多条关系');
await page.getByRole('button',{name:'新建故事',exact:true}).click();
await page.getByRole('dialog').getByRole('button',{name:'新建故事',exact:true}).click();
await page.getByRole('textbox',{name:'故事名称',exact:true}).fill('空白故事');
await page.getByRole('button',{name:'保存故事信息',exact:true}).click();
await expect(page.getByRole('heading',{name:'一段故事，从相遇开始'})).toBeVisible();
results.push('新建空图和故事信息编辑');
await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(globalThis.originalAtlas)});
await page.getByRole('button',{name:'确认导入',exact:true}).click();
await page.getByRole('combobox',{name:'按阵营筛选'}).selectOption('花家');
await expect(page.locator('.character-item')).toHaveCount(3);
await page.getByRole('combobox',{name:'按阵营筛选'}).selectOption('');
await page.getByRole('button',{name:'图谱设置',exact:true}).click();
await page.getByRole('combobox',{name:'自动布局方式'}).selectOption('circle');
await page.getByRole('button',{name:'完成',exact:true}).click();
await page.getByRole('button',{name:'图谱设置',exact:true}).click();
await page.getByRole('combobox',{name:'自动布局方式'}).selectOption('fcose');
await page.getByRole('button',{name:'完成',exact:true}).click();
await page.getByRole('button',{name:'适应画布',exact:true}).click();
results.push('阵营筛选与两种自动布局');
return {passed:results, errors:globalThis.atlasErrors};
