const { app, dialog } = require('electron')
const path = require('node:path')
const fs = require('node:fs/promises')
const assert = require('node:assert/strict')
const results = path.resolve(__dirname, '../test-results')
app.setPath('userData', path.join(results, 'electron-profile'))
app.setPath('sessionData', path.join(results, 'electron-session'))
app.on('browser-window-created', (_, win) => {
  win.hide()
  win.webContents.once('did-finish-load', async () => {
    try {
      await fs.mkdir(results, { recursive: true })
      // Wait for Vue's asynchronous local load to finish, without a fixed sleep.
      const visible = await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const id=setInterval(()=>{if(document.querySelector('.graph-canvas canvas')&&document.body.innerText.includes('已自动保存')){clearInterval(id);resolve(document.body.innerText)}else if(++n>100){clearInterval(id);reject(new Error('UI did not become ready'))}},50)})`)
      const environment = await win.webContents.executeJavaScript(`({bridge:typeof window.desktop.save, node:typeof window.require, secure:window.isSecureContext})`)
      assert.equal(environment.bridge, 'function')
      assert.equal(environment.node, 'undefined')
      const current = await win.webContents.executeJavaScript('window.desktop.load()')
      if (process.argv.includes('--verify-persist')) {
        assert.equal(current.data.title, '桌面持久化验证')
        assert.match(visible, /桌面持久化验证/)
        assert.match(visible, /2 位角色/)
        console.log('PASS: Native Electron relaunch restores title, characters and relationships.')
      } else {
        const png = await win.webContents.capturePage()
        await fs.writeFile(path.join(results, 'desktop-app.png'), png.toPNG())
        const fixture = { version: 1, title: '桌面持久化验证', description: 'IPC smoke test', characters: [{id:'a',name:'甲'},{id:'b',name:'乙'}], relations: [{id:'r',from:'a',to:'b',label:'朋友',direction:'two-way'}] }
        await win.webContents.executeJavaScript(`window.desktop.save(${JSON.stringify(fixture)})`)
        const loaded = await win.webContents.executeJavaScript('window.desktop.load()')
        assert.deepEqual(loaded.data, fixture)
        await win.webContents.executeJavaScript(`Promise.all([window.desktop.save(${JSON.stringify({...fixture,title:'中间快照'})}),window.desktop.save(${JSON.stringify(fixture)})])`)
        const onDisk = JSON.parse(await fs.readFile(path.join(app.getPath('userData'), 'atlas.json'), 'utf8'))
        const backup = JSON.parse(await fs.readFile(path.join(app.getPath('userData'), 'atlas.json.bak'), 'utf8'))
        assert.equal(onDisk.title, fixture.title)
        assert.equal(backup.title, '中间快照')
        const imageFile = path.join(results, 'avatar.png')
        await fs.writeFile(imageFile, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9ioAAAAASUVORK5CYII=', 'base64'))
        const importFile = path.join(results, 'import.json')
        await fs.writeFile(importFile, JSON.stringify({...fixture, characters:[{id:'a',name:'甲',avatar:'avatar.png'},{id:'b',name:'乙',avatar:'../package.json'}]}))
        dialog.showOpenDialog = async () => ({canceled:false,filePaths:[importFile]})
        const imported = await win.webContents.executeJavaScript('window.desktop.importJson()')
        assert.match(imported.data.characters[0].avatar, /^data:image\/png;base64,/)
        assert.equal(imported.data.characters[1].avatar, '')
        assert.equal(imported.warnings.length, 1)
        const exportedFile = path.join(results, 'export.json')
        dialog.showSaveDialog = async () => ({canceled:false,filePath:exportedFile})
        assert.equal(await win.webContents.executeJavaScript(`window.desktop.exportJson(${JSON.stringify(fixture)})`), true)
        assert.deepEqual(JSON.parse(await fs.readFile(exportedFile, 'utf8')), fixture)
        dialog.showOpenDialog = async () => ({canceled:true,filePaths:[]})
        assert.equal(await win.webContents.executeJavaScript('window.desktop.importJson()'), null)
        console.log('PASS: Native Electron renderer, isolated preload, JSON save/load, ordered atomic writes, backup, image resolution, import cancellation and JSON export.')
      }
      await fs.writeFile(path.join(results, process.argv.includes('--verify-persist') ? 'relaunch-result.json' : 'desktop-result.json'), JSON.stringify({passed:true, environment, time:new Date().toISOString()},null,2))
      app.exit(0)
    } catch (error) { console.error(error); await fs.writeFile(path.join(results, 'desktop-failure.txt'), error.stack || String(error)); app.exit(1) }
  })
})
if (process.argv.includes('--seed-example')) {
  const syncFs = require('node:fs')
  syncFs.mkdirSync(app.getPath('userData'), { recursive: true })
  syncFs.writeFileSync(path.join(app.getPath('userData'), 'atlas.json'), syncFs.readFileSync(path.join(__dirname, '../examples/云川旧事.json')))
}
require(process.argv.includes('--packaged') ? '../release/win-unpacked/resources/app.asar/electron/main.cjs' : '../electron/main.cjs')
setTimeout(() => { console.error('Smoke test timed out'); app.exit(1) }, 30000).unref()
