// Run through Tabbit against the isolated 5199 test server only.
assert(page.url().startsWith('http://127.0.0.1:5199/'), 'Use the isolated test server only');
await page.evaluate(async()=>{
  const response=await fetch('/api/library'),current=await response.json();
  const first=current.data.graphs[0];first.data.characters=first.data.characters.filter(c=>c.name!=='测试新增人物');first.data.title='云川旧事';
  const result=await fetch('/api/library',{method:'PUT',headers:{'Content-Type':'application/json','X-Zhiling-Client':'local'},body:JSON.stringify({revision:current.revision,data:{...current.data,activeId:first.id,graphs:[first],localLayouts:{},nodeSize:1}})});
  if(!result.ok)throw new Error('Fixture reset failed');
});
await page.reload();
await page.waitForFunction(()=>document.querySelector('.graph-engine')?._cyreg?.cy?.nodes().length===12);
const positions=()=>page.evaluate(()=>Object.fromEntries(document.querySelector('.graph-engine')._cyreg.cy.nodes().map(n=>[n.id(),{...n.position()}])));
await page.evaluate(()=>{const cy=document.querySelector('.graph-engine')._cyreg.cy;cy.nodes().forEach((n,i)=>n.position({x:(i%4)*400,y:Math.floor(i/4)*350}));cy.nodes().first().emit('dragfree');cy.fit();});
const manual=await positions();
await page.getByLabel('按阵营筛选').selectOption('花家');
await page.getByLabel('按阵营筛选').selectOption('云岫门');
await page.getByLabel('按阵营筛选').selectOption('');
expect(await positions()).toEqual(manual);
await page.getByLabel('图谱设置',{exact:true}).click();
await page.getByLabel('角色头像大小 5 档',{exact:true}).check();
const sizes=await page.evaluate(()=>{const cy=document.querySelector('.graph-engine')._cyreg.cy;return {node:cy.nodes()[0].style('font-size'),edge:cy.edges()[0].style('font-size'),width:cy.edges()[0].style('width')};});
assert.equal(sizes.node,'27px');assert.equal(sizes.edge,'27px');assert(Math.abs(parseFloat(sizes.width)-2.34)<1e-6);
await page.getByRole('button',{name:'完成',exact:true}).click();
await page.locator('.character-item').filter({has:page.locator('strong',{hasText:'花盈'})}).click();
await page.getByRole('button',{name:'固定档案',exact:true}).click();
await page.locator('.character-item').filter({has:page.locator('strong',{hasText:'花绫'})}).click();
await expect(page.locator('.profile h2')).toHaveText('花盈');
await expect(page.locator('.character-item.active strong')).toHaveText('花绫');
await page.getByRole('button',{name:'取消固定档案',exact:true}).click();
await expect(page.locator('.profile h2')).toHaveText('花绫');
await page.getByRole('button',{name:'关闭详情',exact:true}).click();
const beforeAdd=await positions();
await page.getByRole('button',{name:'添加角色',exact:true}).first().click();
await page.getByLabel('角色名称', {exact:false}).fill('测试新增人物');
await page.getByRole('button',{name:'添加角色',exact:true}).last().click();
await page.waitForFunction(()=>document.querySelector('.graph-engine')._cyreg.cy.nodes().length===13);
const afterAdd=await positions();for(const [id,pos] of Object.entries(beforeAdd))expect(afterAdd[id]).toEqual(pos);
await page.getByLabel('切换关系网',{exact:true}).click();
await page.getByRole('button',{name:'新建关系网',exact:true}).click();
await page.getByLabel('复制已有关系网',{exact:true}).selectOption({label:'云川旧事'});
await expect(page.getByLabel('关系网名称',{exact:true})).toHaveValue('云川旧事-副本');
await page.getByLabel('关系网名称',{exact:true}).fill('独立副本验证');
await page.getByRole('button',{name:'创建关系网',exact:true}).click();
await expect(page.locator('.project-title')).toHaveText('独立副本验证');
expect(await positions()).toEqual(afterAdd);
await page.getByLabel('使用帮助',{exact:true}).click();
const alignment=await page.locator('.help-footer').evaluate(e=>{const p=e.querySelector('p').getBoundingClientRect(),b=e.querySelector('button').getBoundingClientRect();return Math.abs(p.bottom-b.bottom)});
assert(alignment<1);
const screenshot=await page.screenshot({fullPage:false});
await page.getByRole('button',{name:'开始创作',exact:true}).click();
await page.getByRole('button',{name:'全屏',exact:true}).click();
await page.waitForFunction(()=>!!document.fullscreenElement||document.body.innerText.includes('无法进入全屏'));
const browserFullscreen=await page.evaluate(()=>!!document.fullscreenElement);
if(browserFullscreen){
  const hidden=await page.locator('.app-header,.sidebar,.inspector,.status-bar,.canvas-controls,.canvas-caption').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width===0||e.getBoundingClientRect().height===0));assert(hidden);
  await page.keyboard.press('Escape');
  await expect(page.getByLabel('图谱设置',{exact:true})).toBeVisible();
}
await page.getByRole('button',{name:'保存',exact:true}).click();
await expect(page.locator('.status-bar')).toContainText('已自动保存');
await page.reload();
await expect(page.locator('.project-title')).toHaveText('独立副本验证');
expect(await positions()).toEqual(afterAdd);
return {passed:true,sizes,filterPreserved:true,newNodePreserved:true,pin:true,copy:true,browserFullscreen,reload:true,copyrightBottomDifference:alignment,screenshot};
